version: '3.8'
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=wavely
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_PASSWORD=123456
        networks:
            - backend_network
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'localhost',
                    '-u',
                    'root',
                    '-p$$MYSQL_ROOT_PASSWORD',
                ]
            timeout: 20s
            retries: 10
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - backend_network
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            timeout: 20s
            retries: 10

volumes:
    mysql_data:
    redis_data:

networks:
    backend_network:
